[Data][Docs] Fix `hf_quick_start.py` (#35240)
`hf_quick_start.py` was failing with

> ValueError: ArrowVariableShapedTensorArray only supports heterogeneous-shaped tensor collections, not arbitrarily nested ragged tensors. Got arrays: [('dtype=object', 'shape=(1,)'), ('dtype=object', 'shape=(1,)')]

This is because we're returning an object that looks like

```python
{"output": 
    [[{'generated_text': 'Complete this page to stay up to date with our latest news in aviation related news. You can also'}], 
     [{'generated_text': "for me. We could use those resources as time goes on. We'll get to it in the"}]]
}
```

from a UDF.

This PR updates the UDF so it returns object like

```python
{"output": [
    'Complete this page to stay up to date with our latest news in aviation related news. You can also', 
    "for me. We could use those resources as time goes on. We'll get to it in the"
]}
```

Signed-off-by: Balaji Veeramani <balaji@anyscale.com>