[serve] Better surfacing of errors in serve status (#34773)
1. Surface tracebacks from constructor failures.
Output from `serve status`:
```
name: default
app_status:
  status: DEPLOY_FAILED
  message: |-
    Deploying app 'default' failed:
    ray::deploy_serve_application() (pid=15878, ip=192.168.1.14)
      File "/Users/cindyz/ray/python/ray/serve/controller.py", line 947, in deploy_serve_application
        serve.run(app, name=name, route_prefix=route_prefix)
      File "/Users/cindyz/ray/python/ray/serve/api.py", line 539, in run
        client.deploy_application(
      File "/Users/cindyz/ray/python/ray/serve/_private/client.py", line 43, in check
        return f(self, *args, **kwargs)
      File "/Users/cindyz/ray/python/ray/serve/_private/client.py", line 299, in deploy_application
        self._wait_for_deployment_healthy(deployment_name)
      File "/Users/cindyz/ray/python/ray/serve/_private/client.py", line 183, in _wait_for_deployment_healthy
        raise RuntimeError(
    RuntimeError: Deployment default_Fail is UNHEALTHY: The Deployment failed to start 3 times in a row. This may be due to a problem with the deployment constructor or the initial health check failing. See controller logs for details. Retrying after 1 seconds. Error:
    ray::ServeReplica:default_Fail.is_initialized() (pid=15919, ip=192.168.1.14, repr=<ray.serve._private.replica.ServeReplica:default_Fail object at 0x1257772e0>)
      File "/Users/cindyz/miniforge3/envs/ray/lib/python3.8/concurrent/futures/_base.py", line 437, in result
        return self.__get_result()
      File "/Users/cindyz/miniforge3/envs/ray/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
        raise self._exception
      File "/Users/cindyz/ray/python/ray/serve/_private/replica.py", line 234, in is_initialized
        await self._initialize_replica()
      File "/Users/cindyz/ray/python/ray/serve/_private/replica.py", line 150, in initialize_replica
        await sync_to_async(_callable.__init__)(*init_args, **init_kwargs)
      File "/Users/cindyz/Desktop/constructor_fail.py", line 16, in __init__
        raise Exception("I need to know about this!")
    Exception: I need to know about this!
  deployment_timestamp: 1682476137.8513532
deployment_statuses:
- name: default_Fail
  status: UNHEALTHY
  message: |-
    The Deployment failed to start 3 times in a row. This may be due to a problem with the deployment constructor or the initial health check failing. See controller logs for details. Retrying after 1 seconds. Error:
    ray::ServeReplica:default_Fail.is_initialized() (pid=15919, ip=192.168.1.14, repr=<ray.serve._private.replica.ServeReplica:default_Fail object at 0x1257772e0>)
      File "/Users/cindyz/miniforge3/envs/ray/lib/python3.8/concurrent/futures/_base.py", line 437, in result
        return self.__get_result()
      File "/Users/cindyz/miniforge3/envs/ray/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
        raise self._exception
      File "/Users/cindyz/ray/python/ray/serve/_private/replica.py", line 234, in is_initialized
        await self._initialize_replica()
      File "/Users/cindyz/ray/python/ray/serve/_private/replica.py", line 150, in initialize_replica
        await sync_to_async(_callable.__init__)(*init_args, **init_kwargs)
      File "/Users/cindyz/Desktop/constructor_fail.py", line 16, in __init__
        raise Exception("I need to know about this!")
    Exception: I need to know about this!
```

2. Serializes exceptions from the replica actor, so that they are displayed properly when surfaced through the controller.